In [44]:
import numpy as np


In [45]:
a=np.array([1,2,3])

In [46]:
b=np.array([(1.5,2,3),(4,5,6)],dtype=float)

In [47]:
c=np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]],dtype=float)

In [48]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
np.ones((2,3,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [90]:
e=np.linspace(0,2,9)

In [91]:
np.arange(10,25,5)

array([10, 15, 20])

In [92]:
e

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [93]:
np.full((2,2),7)

array([[7, 7],
       [7, 7]])

In [54]:
x=np.eye(2)
y=np.random.random((2,2))
x

array([[1., 0.],
       [0., 1.]])

In [55]:
y

array([[0.23644134, 0.62479348],
       [0.07081279, 0.12352335]])

In [56]:
np.shape(a)

(3,)

In [94]:
np.shape(c)

(2, 2, 3)

In [95]:
np.shape(b)

(2, 3)

In [59]:
np.ndim(a)

1

In [60]:
np.ndim(b)

2

In [61]:
np.ndim(c)

3

In [62]:
np.size(a)

3

In [63]:
np.size(b)

6

In [64]:
np.size(c)

12

In [65]:
a.dtype

dtype('int32')

In [66]:
b.dtype

dtype('float64')

In [67]:
c.dtype

dtype('float64')

In [68]:
a.dtype.name

'int32'

In [69]:
b.dtype.name

'float64'

In [70]:
c.dtype.name

'float64'

In [71]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
x=np.multiply(b,b)

In [97]:
x

array([[ 2.25,  4.  ,  9.  ],
       [16.  , 25.  , 36.  ]])

In [99]:
np.divide(b,a)

array([[1.5, 1. , 1. ],
       [4. , 2.5, 2. ]])

In [100]:
np.add(b,b)

array([[ 3.,  4.,  6.],
       [ 8., 10., 12.]])

In [101]:
np.subtract(b,b)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [77]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [78]:
np.sqrt(b)

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [79]:
np.sqrt(c)

array([[[1.22474487, 1.41421356, 1.73205081],
        [2.        , 2.23606798, 2.44948974]],

       [[1.73205081, 1.41421356, 1.        ],
        [2.        , 2.23606798, 2.44948974]]])

In [102]:
np.add(c,c)

array([[[ 3.,  4.,  6.],
        [ 8., 10., 12.]],

       [[ 6.,  4.,  2.],
        [ 8., 10., 12.]]])

In [103]:
np.min(b)

np.float64(1.5)

In [104]:
np.max(b)

np.float64(6.0)

In [105]:
np.cumsum(b)

array([ 1.5,  3.5,  6.5, 10.5, 15.5, 21.5])

In [84]:
np.mean(a)

np.float64(2.0)

In [106]:
np.median(b)

np.float64(3.5)

In [86]:
np.std(a)

np.float64(0.816496580927726)